### ISSUE TITLE
steghide algorithm

### ISSUE THREAD

**Issue by adpoint** [StegHigh/steghide#1]
hi,Stefan Hetzl:
    I had one question to ask, it's algorithm about steghide, is LSB(Least Significant Bit)?

thanks!

**Comment by Aminuxer** [comment]
No, not so simple =)

LSB applied only for some parts of secret data.
steghide use more tricky features - mathematical graph theory  for swap lsb-bits between pixels in graph for maximum usage of existing data in cover file.

**Comment by StefanoDeVuono** [comment]
Hello @adpoint and @Aminuxer. I don't know if you're still following this repo, but we've created an org StegHigh to maintain it. We've transferred the repository, but unfortunately we cannot transfer issues.

Please copy this issue to the [new repository](https://github.com/StegHigh/steghide/issues).

Alternatively, if you feel this is better as a topic of discussion, please post in [StegHigh discussions](https://github.com/orgs/StegHigh/discussions).

Thanks!
